### ISSUE TITLE
Issues with mod

### ISSUE THREAD

**Issue by JJoeDev** [Lukkaggeskola/Zoloz_menu_with_KickMod#1]
Hi. I just want to say that I am deeply disappointed in you that you stole all kinds of code and only changed a few booleans.
You even stole my old long arms mod and it even looks worse in this dumpster than when I wrote it.
Instead of changing a few true false statements, make mods that are actually worth it. But you are probably banned from the server now, witch is 100% deserved.

**Comment by CletusOnTop** [comment]
i wrote (NOT MINE) dude

**Comment by JJoeDev** [comment]
Well, then you forked it and still posted it in the discord, so its still well deserved :D
